type arr = [number,string,string,string,string,string,string]

export const Commu_arry:arr[] = [
    [1,'HiringInfo','works at Unisys India','https://dslntlv9vhjr4.cloudfront.net/bowls_images/035wYdyAZ9nWH.jpg',"Anyone who wants to apply to NTT Data, DM me with Job ID. can refer you.Good luck",'','3h'],
    [2,'HiringInfo','works at Infosys','https://dslntlv9vhjr4.cloudfront.net/bowls_images/035wYdyAZ9nWH.jpg',"Let me know if anyone is looking for below roles in Infosys",'https://dslntlv9vhjr4.cloudfront.net/posts_images/O0sYu6UpJUEec.jpg','19h'],
    [3,'HiringInfo','Tejas Ranadive','https://dslntlv9vhjr4.cloudfront.net/bowls_images/035wYdyAZ9nWH.jpg',"Good morning/afternoon. My name is Tejas Ranadive and I'm an experienced Executive Producer with over 18 years in the programming and production industry. I have proven expertise in handling all aspects of Pre- Production and post-production for TV shows,Ad films,Vfx",'','21h'],
    [4,'HiringInfo','Front END Developer','https://dslntlv9vhjr4.cloudfront.net/bowls_images/035wYdyAZ9nWH.jpg',"Hi Everyone,I'm a React.js developer with 2 Years of experience looking for new opportunities to leverage my skills and contribute to exciting projects .",'','1d'],
    [5,'Referral and Opportunities','Technical Support Engineer II','https://www.glassdoor.com/images/bowls/headers/default-grey.png',"I have 5 years of experience in the filed of Linux, I was working as a Technical support Engineer, currently I am looking for Linux related post as I have good knowledge of Linux commands, cronjobs, writing query SQL in MYSQL, basic knowledge of Shell Scripting.",'','10m'],
    [6,'Referral and Opportunities','works at Pixis','https://www.glassdoor.com/images/bowls/headers/default-grey.png',"I am looking for remote opportunities. Motion designer 6+ years of experience Kindly reach out to me at +919711284264. Current 16.50 Ipa Expected 30 Ipa. 60 days notice period, negotiable.",'','30m'],
    [7,'Big 4 Discussions!','works at KPMG','	https://dslntlv9vhjr4.cloudfront.net/bowls_images/18SaaIiCOZhvc.jpg',"Hi, Does anyone have idea on what is the salary we can expect after getting promoted to senior associate from Associate 2 in KGS Tax.",'','56m'],
    [8,'Big 4 Discussions!','Customer Support Representative','https://dslntlv9vhjr4.cloudfront.net/bowls_images/18SaaIiCOZhvc.jpg',"Tech Mahindra is the worst company I’ve ever worked in. They lie about the in-hand salary. Our whole batch and previous batch has been lied about salary and all are receiving 4-5k lesser than we were promised.",'https://dslntlv9vhjr4.cloudfront.net/posts_images/zClknJ4HCecVU.png','1d'],
    [9,'Big 4 Discussions!','works at Accenture','https://dslntlv9vhjr4.cloudfront.net/bowls_images/18SaaIiCOZhvc.jpg',"Can anyone please refer me to EY GDS for SAP PP QM role. I have 5 YOE and my LWD is 7 July.EY Ey global delivery services Deloitte USI",'','2d'],
    [10,'PwC IAC','Process Associate','https://dslntlv9vhjr4.cloudfront.net/bowls_images/PBYuAWuTvXP9f.jpg',"Hi can anyone refer me in Pwc in this job. Kindly help me.I will be highly obliged if anyone could refer me. I have applied numerous time but still nothing is happening.",'https://dslntlv9vhjr4.cloudfront.net/posts_images/0YpX0oWto2ff0.png','6d']
]