version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:saransathish@jobsdb.cvkw0mg4a8as.eu-north-1.rds.amazonaws.com:5432/glassdoor
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saransathish
      POSTGRES_DB: glassdoor
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
